### ISSUE TITLE
When the initial page redirects, the BridgeDelegate.location becomes stale

### ISSUE THREAD

**Issue by adampal** [hotwired/strada-ios#23]
When the very first URL loaded by a Turbo.VisitableViewController is redirected by the Rails app, the `location` constant in the BridgeDelegate is set to the initial URL, not the redirected URL.  As a result, any BridgeComponents on the page will ignore messages because the `location` does not match the `message.metadata?.url`.

Any subsequent page loads, even if they include redirects, will set the `location` correctly and BridgeComponents will work.

I created minimal [Rails](https://github.com/adampal/stradabug-web) and [iOS](https://github.com/adampal/stradabug-ios) repos to reproduce the bug. The Rails repo is a basic `rails new` with all the defaults and really just adds the `bridge--hello` controller and views.

The iOS repo starts from the Strada-iOS demo and just adds a `helloComponent`.

Each repo only adds a single commit ([rails commit](https://github.com/adampal/stradabug-web/commit/19820c9c231e6c1dc10abea267b995d37e63aa66), [iOS commit](https://github.com/adampal/stradabug-ios/commit/443bc28f36b4d4b1b47aceb1b4e99b1bacd45d9e)) so it's easy to see what I've added/changed to reproduce the bug.

If you clone the repos and run it locally, you can toggle the behaviour by setting the `Demo.current` in the iOS repo to either `local` or `noRedirect`:
- when set to `noRedirect` the rootURL is set to the URL of the first page. The app will load and the BridgeComponent is loaded and works correctly.
- when set to `local` the rootURL is set to a different URL that redirects to the URL of the first page of the app.  

Even though they both end up on the same page, in the `local` version the BridgeComponent will ignore messages because of the stale `location` attribute.

You can test subsequent page loads by clicking the links in the nav at the top. All subsequent page loads work correctly, whether they redirect or not.

From looking at the Strada debug logs, it seems that when a URL is redirected, we are supposed to get all lifecycle callbacks triggered twice. Once for the initial URL then again for the final destination URL.  However, when the very first URL of the application redirects, this doesn't happen and we just end up with one set of lifecycle events.

I think this may actually be a bug in the Turbo-iOS adapter not here in Strada, but I'm hoping someone with more knowledge than me can point me in the right direction of where/how to get it fixed.

**Comment by joemasilotti** [comment]
Confirming that this is reproducible and I'd love to get it fixed!

**Comment by joemasilotti** [comment]
@adampal, can you give #24 a go and see if it fixes the issue for you?

**Comment by adampal** [comment]
@joemasilotti can confirm #24 fixes this issue!

**Comment by joemasilotti** [comment]
Excellent, thanks @adampal!
